/** @type {import('tailwindcss').Config} */
/* Theme migrated from js/tailwind-site-config.js (Y2K / Vulf palette). */
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
    "./partials/**/*.html",
    "./js/**/*.js",
    "./calendar-add-script/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#120422",
        secondary: "#ffafd2",
        "surface-bright": "#423257",
        "primary-fixed": "#55ffa9",
        "on-primary": "#00391f",
        "on-primary-fixed-variant": "#005230",
        "on-surface": "#eedcff",
        "inverse-on-surface": "#39294e",
        primary: "#f4fff4",
        "surface-tint": "#00e38d",
        "on-tertiary-container": "#6051c2",
        "on-primary-fixed": "#002110",
        background: "#0d0517",
        "on-secondary-fixed": "#3d0025",
        "tertiary-fixed-dim": "#c7bfff",
        "on-background": "#eedcff",
        "surface-container-high": "#2d1b4d",
        "surface-container": "#251540",
        "primary-container": "#00ff9f",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#180065",
        "on-secondary-container": "#570037",
        tertiary: "#fffaff",
        "surface-dim": "#0d0517",
        error: "#ffb4ab",
        "on-tertiary-fixed-variant": "#4433a4",
        "tertiary-container": "#e1dbff",
        "primary-fixed-dim": "#00e38d",
        "on-error": "#690005",
        outline: "#849587",
        "tertiary-fixed": "#e5deff",
        "error-container": "#93000a",
        "on-tertiary": "#2c148e",
        "secondary-container": "#ff41af",
        "on-secondary-fixed-variant": "#8b005b",
        "surface-container-highest": "#3d2d52",
        surface: "#120422",
        "on-secondary": "#63003f",
        "secondary-fixed-dim": "#ffafd2",
        "surface-container-low": "#1a0b2e",
        "on-surface-variant": "#c8b8d8",
        "on-primary-container": "#007144",
        "secondary-fixed": "#ffd8e7",
        "outline-variant": "#3a4a3f",
        "surface-variant": "#3d2d52",
        "inverse-surface": "#eedcff",
        "inverse-primary": "#006d41",
        "deep-purple": "#0d0517",
      },
      fontFamily: {
        mono: ["Vulf Mono", "ui-monospace", "monospace"],
        sans: ["Vulf Sans", "system-ui", "sans-serif"],
      },
      borderRadius: { DEFAULT: "4px", lg: "8px", xl: "12px", full: "9999px" },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
