/**
 * photo-upload.js
 *
 * Secure photo upload panel for the photo album page.
 * Activated by visiting photo-album.html?upload
 *
 * Security model:
 *   - A GitHub Personal Access Token (PAT) is stored encrypted using AES-GCM.
 *   - The encryption key is derived from a password via PBKDF2 (200k iterations, SHA-256).
 *   - Wrong password → decryption fails → no API access.
 *   - Correct password → PAT is decrypted in-memory and used for GitHub API calls only.
 *   - Run setup-encryption.html locally to generate your ENCRYPTED_PAT blob.
 */

// ── Config ──────────────────────────────────────────────────────────────────
const REPO_OWNER = "jarretttthompson";
const REPO_NAME  = "jarretttthompson.github.io";
const PHOTO_DIR  = "images/photo album";
const MANIFEST   = "photo-album.json";
const MAX_PX     = 1600;   // longest side after resize (px)
const JPEG_Q     = 0.85;   // JPEG compression quality

// ── Encrypted PAT ───────────────────────────────────────────────────────────
// Replace this null with the object generated by setup-encryption.html
// e.g.  const ENCRYPTED_PAT = { salt: "…", iv: "…", data: "…" };
const ENCRYPTED_PAT = null;

// ── Crypto helpers ──────────────────────────────────────────────────────────
function b64ToBytes(b64) {
  return Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
}

async function deriveKey(password, saltBytes) {
  const raw = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveKey"],
  );
  return crypto.subtle.deriveKey(
    { name: "PBKDF2", salt: saltBytes, iterations: 200_000, hash: "SHA-256" },
    raw,
    { name: "AES-GCM", length: 256 },
    false,
    ["decrypt"],
  );
}

async function decryptPat(password, blob) {
  const salt    = b64ToBytes(blob.salt);
  const iv      = b64ToBytes(blob.iv);
  const data    = b64ToBytes(blob.data);
  const key     = await deriveKey(password, salt);
  const decoded = await crypto.subtle.decrypt({ name: "AES-GCM", iv }, key, data);
  return new TextDecoder().decode(decoded);
}

// ── Image helpers ────────────────────────────────────────────────────────────
function resizeAndEncode(file) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    const url = URL.createObjectURL(file);
    img.onload = () => {
      URL.revokeObjectURL(url);
      const { naturalWidth: w, naturalHeight: h } = img;
      const scale  = Math.min(1, MAX_PX / Math.max(w, h));
      const cw     = Math.round(w * scale);
      const ch     = Math.round(h * scale);
      const canvas = Object.assign(document.createElement("canvas"), { width: cw, height: ch });
      canvas.getContext("2d").drawImage(img, 0, 0, cw, ch);
      canvas.toBlob(
        (blob) => {
          const reader = new FileReader();
          reader.onload  = () => resolve(reader.result.split(",")[1]); // base64 only
          reader.onerror = reject;
          reader.readAsDataURL(blob);
        },
        "image/jpeg",
        JPEG_Q,
      );
    };
    img.onerror = reject;
    img.src = url;
  });
}

// ── GitHub API helpers ───────────────────────────────────────────────────────
function ghFetch(path, token, opts = {}) {
  return fetch(
    `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${encodeURIComponent(path).replace(/%2F/g, "/")}`,
    {
      ...opts,
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
        ...(opts.headers ?? {}),
      },
    },
  );
}

async function getFile(path, token) {
  const res = await ghFetch(path, token);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`GitHub GET ${path} failed: ${res.status}`);
  return res.json(); // { content (base64 w/ newlines), sha, … }
}

async function putFile(path, token, message, content64, sha) {
  const body = { message, content: content64 };
  if (sha) body.sha = sha;
  const res = await ghFetch(path, token, { method: "PUT", body: JSON.stringify(body) });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.message ?? `GitHub PUT ${path} failed: ${res.status}`);
  }
  return res.json();
}

// ── Upload orchestration ────────────────────────────────────────────────────
async function uploadPhoto({ file, caption, token, onStatus }) {
  onStatus("Compressing image…");
  const imageB64 = await resizeAndEncode(file);

  const ts       = Date.now();
  const filename = `upload-${ts}.jpg`;
  const imgPath  = `${PHOTO_DIR}/${filename}`;

  onStatus("Uploading image to GitHub…");
  await putFile(imgPath, token, `photo: add ${filename}`, imageB64, null);

  onStatus("Updating photo manifest…");
  const mf      = await getFile(MANIFEST, token);
  let photos    = [];
  let sha;
  if (mf) {
    sha    = mf.sha;
    photos = JSON.parse(atob(mf.content.replace(/\n/g, "")));
  }
  const entry      = { src: imgPath, alt: caption.trim() || "N" };
  photos.unshift(entry); // newest first → shows at top of album
  const newContent = btoa(unescape(encodeURIComponent(JSON.stringify(photos, null, 2))));
  await putFile(MANIFEST, token, "photo: update manifest", newContent, sha);

  onStatus("✓ Uploaded! Your photo will appear in the album in about 60 seconds.");
}

// ── Styles ───────────────────────────────────────────────────────────────────
const PANEL_CSS = `
  #photo-upload-panel input[type="text"],
  #photo-upload-panel input[type="password"] {
    background: #0d0517;
    color: #00ff9f;
    border: 1px solid rgba(0,255,159,0.35);
    border-radius: 6px;
    padding: 0.4rem 0.75rem;
    font-family: inherit;
    font-size: 0.875rem;
    outline: none;
    transition: border-color 0.15s;
  }
  #photo-upload-panel input:focus {
    border-color: rgba(0,255,159,0.75);
  }
  #photo-upload-panel .upl-btn {
    background: transparent;
    border: 1px solid #00ff9f;
    color: #00ff9f;
    border-radius: 6px;
    padding: 0.45rem 1.1rem;
    font-family: inherit;
    font-size: 0.875rem;
    cursor: pointer;
    transition: background 0.15s, color 0.15s;
    white-space: nowrap;
  }
  #photo-upload-panel .upl-btn:hover:not(:disabled) {
    background: rgba(0,255,159,0.12);
  }
  #photo-upload-panel .upl-btn:disabled {
    opacity: 0.45;
    cursor: default;
  }
  #photo-upload-panel .upl-btn-wide {
    display: block;
    width: 100%;
    text-align: center;
    padding: 0.6rem;
  }
  #photo-upload-panel .upl-file-label {
    display: block;
    border: 1px dashed rgba(0,255,159,0.5);
    color: rgba(0,255,159,0.8);
    border-radius: 8px;
    padding: 1.25rem;
    text-align: center;
    cursor: pointer;
    font-size: 0.875rem;
    transition: border-color 0.15s, color 0.15s;
    margin-bottom: 0.75rem;
  }
  #photo-upload-panel .upl-file-label:hover {
    border-color: #00ff9f;
    color: #00ff9f;
  }
  #upl-preview {
    display: none;
    max-width: 100%;
    border-radius: 6px;
    margin-bottom: 0.75rem;
    border: 1px solid rgba(0,255,159,0.3);
  }
`;

// ── Panel HTML ───────────────────────────────────────────────────────────────
const PANEL_HTML = `
  <h2 class="panel-heading text-lg mb-1" style="font-size:0.95rem;letter-spacing:0.08em">[ upload photo ]</h2>
  <p class="panel-kicker mb-4">add a photo to the album</p>

  <!-- LOCK SCREEN -->
  <div id="upl-lock">
    <div style="display:flex;gap:0.5rem;align-items:center;flex-wrap:wrap">
      <input id="upl-pw" type="password" placeholder="password"
        autocomplete="current-password" style="flex:1;min-width:0" />
      <button id="upl-unlock" class="upl-btn">unlock</button>
    </div>
    <p id="upl-lock-err"
      style="color:#ff41af;font-size:0.8rem;margin-top:0.4rem;display:none">
      incorrect password
    </p>
  </div>

  <!-- UPLOAD FORM (hidden until unlocked) -->
  <div id="upl-form" style="display:none">
    <label class="upl-file-label" for="upl-file">
      tap to choose a photo
      <input id="upl-file" type="file" accept="image/*" style="display:none" />
    </label>
    <img id="upl-preview" src="" alt="preview" />
    <input id="upl-caption" type="text" placeholder="caption (optional)"
      style="display:block;width:100%;margin-bottom:0.75rem;box-sizing:border-box" />
    <button id="upl-submit" class="upl-btn upl-btn-wide">upload</button>
    <p id="upl-status"
      style="font-size:0.8rem;margin-top:0.6rem;color:rgba(0,255,159,0.7);min-height:1.2em"></p>
  </div>
`;

// ── Init ─────────────────────────────────────────────────────────────────────
export function initPhotoUpload() {
  // Only activate when ?upload is in the URL
  if (!new URLSearchParams(location.search).has("upload")) return;

  // Inject scoped styles
  const style = document.createElement("style");
  style.textContent = PANEL_CSS;
  document.head.appendChild(style);

  // Build panel
  const panel = document.createElement("div");
  panel.id        = "photo-upload-panel";
  panel.className = "neon-inner-panel relative p-4 md:p-6";
  panel.style.marginBottom = "1.25rem";
  panel.innerHTML = PANEL_HTML;

  // Insert before the album wall
  const wall   = document.querySelector(".album-wall");
  const parent = wall?.parentElement ?? document.querySelector(".album-main") ?? document.querySelector(".site-shell-content");
  if (!parent) return;
  parent.insertBefore(panel, wall ?? parent.firstChild);

  // Element references
  const pwInput   = panel.querySelector("#upl-pw");
  const unlockBtn = panel.querySelector("#upl-unlock");
  const lockErr   = panel.querySelector("#upl-lock-err");
  const lockDiv   = panel.querySelector("#upl-lock");
  const formDiv   = panel.querySelector("#upl-form");
  const fileInput = panel.querySelector("#upl-file");
  const preview   = panel.querySelector("#upl-preview");
  const captionIn = panel.querySelector("#upl-caption");
  const submitBtn = panel.querySelector("#upl-submit");
  const statusEl  = panel.querySelector("#upl-status");

  let token = null; // set after successful unlock

  // ── Unlock ─────────────────────────────────────────────────────────────
  async function tryUnlock() {
    lockErr.style.display = "none";
    if (!ENCRYPTED_PAT) {
      lockErr.textContent = "No encrypted token configured — run setup-encryption.html first.";
      lockErr.style.display = "block";
      return;
    }
    unlockBtn.disabled = true;
    try {
      token = await decryptPat(pwInput.value, ENCRYPTED_PAT);
      lockDiv.style.display = "none";
      formDiv.style.display = "block";
    } catch {
      lockErr.style.display = "block";
      pwInput.value = "";
      pwInput.focus();
    } finally {
      unlockBtn.disabled = false;
    }
  }

  unlockBtn.addEventListener("click", tryUnlock);
  pwInput.addEventListener("keydown", (e) => { if (e.key === "Enter") tryUnlock(); });

  // ── File preview ───────────────────────────────────────────────────────
  fileInput.addEventListener("change", () => {
    const file = fileInput.files[0];
    if (!file) return;
    if (preview._objectUrl) URL.revokeObjectURL(preview._objectUrl);
    preview._objectUrl  = URL.createObjectURL(file);
    preview.src         = preview._objectUrl;
    preview.style.display = "block";
  });

  // ── Submit ─────────────────────────────────────────────────────────────
  submitBtn.addEventListener("click", async () => {
    const file = fileInput.files[0];
    if (!file) {
      statusEl.style.color = "#ff41af";
      statusEl.textContent = "Please choose a photo first.";
      return;
    }
    submitBtn.disabled   = true;
    statusEl.style.color = "rgba(0,255,159,0.7)";
    statusEl.textContent = "";

    try {
      await uploadPhoto({
        file,
        caption: captionIn.value,
        token,
        onStatus: (msg) => { statusEl.textContent = msg; },
      });
      // Reset form after success
      fileInput.value      = "";
      captionIn.value      = "";
      preview.style.display = "none";
      if (preview._objectUrl) {
        URL.revokeObjectURL(preview._objectUrl);
        preview._objectUrl = null;
      }
    } catch (err) {
      statusEl.style.color = "#ff41af";
      statusEl.textContent = `Upload failed: ${err.message}`;
    } finally {
      submitBtn.disabled = false;
    }
  });
}
